# services:
#   db:
#     image: mysql:8.0
#     container_name: db_${PROJECT_DIR}
#     volumes:
#       - db-volume:/var/lib/mysql
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
#     networks:
#       - dev

#   phpmyadmin:
#     image: phpmyadmin
#     container_name: phpmyadmin_${PROJECT_DIR}
#     restart: always
#     depends_on:
#       - db
#     ports:
#       - "8080:80"
#     environment:
#       PMA_HOST: db
#     networks:
#       - dev

#   maildev:
#     image: maildev/maildev
#     container_name: maildev_${PROJECT_DIR}
#     command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
#     ports:
#       - "8081:80"
#     restart: always
#     networks:
#       - dev

#   www:
#     build: ./php
#     container_name: ${PROJECT_DIR}
#     env_file:
#       - .env
#     ports:
#       - "8741:80"
#     volumes:
#       - ./php/vhosts:/etc/apache2/sites-enabled
#       - ./${PROJECT_DIR}:/var/www
#       - ~/.gitconfig:/root/.gitconfig:ro
#     restart: always
#     networks:
#       - dev

# volumes:
#   db-volume:

# networks:
#   dev:
#     driver: bridge


services:
  db:
    image: mysql:8.0
    container_name: db_${PROJECT_DIR}
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_${PROJECT_DIR}
    restart: always
    depends_on:
      - db
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: db
    networks:
      - dev

  maildev:
    image: maildev/maildev
    container_name: maildev_${PROJECT_DIR}
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "${MAILDEV_PORT}:80"
    restart: always
    networks:
      - dev

  www:
    build: ./php
    container_name: ${PROJECT_DIR}
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./${PROJECT_DIR}:/var/www
      - ~/.gitconfig:/root/.gitconfig:ro
    restart: always
    networks:
      - dev

volumes:
  db-volume:

networks:
  dev:
    driver: bridge

